apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flink.clusterName }}-jobmanager-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: {{ .Values.flink.clusterName }}
    component: {{ .Values.flink.clusterName }}-jobmanager
    #type: LoadBalancer
