version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
#    image: apache/nifi:1.9.2
    image: 'streamlio/nifi:1.9.0'
    ports:
      - 9090:9090 
      - 8000:8000
      - 8443:8443
      - 10000:10000
    environment:
      - NIFI_WEB_HTTP_PORT=9090
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
      - NIFI_REMOTE_INPUT_SECURE=false
