apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nifi.clusterName }}-nifi
spec:
  type: NodePort
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
    nodePort: 30090
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8443"
    port: 8443
    targetPort: 8443
  - name: "10000"
    port: 10000
    targetPort: 10000
  selector:
    app: {{ .Values.nifi.clusterName }}
    component: {{ .Values.nifi.clusterName }}-nifi
