apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nifi.clusterName }}-zookeeper
spec:
  replicas: {{ .Values.nifi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nifi.clusterName }}
      component: {{ .Values.nifi.clusterName }}-zookeeper
  template:
    metadata:
      labels:
        app: {{ .Values.nifi.clusterName }}
        component: {{ .Values.nifi.clusterName }}-zookeeper
    spec:
      containers:
      - name: {{ .Values.nifi.clusterName }}-zookeeper
        image: {{ .Values.zookeeper.image.name }}:{{ .Values.zookeeper.image.tag }}
        imagePullPolicy: {{ .Values.zookeeper.image.imagePullPolicy }}
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        resources:
          requests:
            cpu: {{ .Values.resources.zookeeper.requests.cpu }}
            memory: {{ .Values.resources.zookeeper.requests.memory }}
