apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flink.cluster_name }}-jobmanager-rest
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
  selector:
    app: {{ .Values.flink.cluster_name }}
    component: {{ .Values.flink.cluster_name }}-jobmanager
